nodeLinker: 'node-modules'

packageExtensions:
  "@angular-devkit/build-angular@19.2.12":
    dependencies:
      "@angular/compiler": ^19.2.10
      vite: 6.2.7
  "@module-federation/cli@0.13.1":
    dependencies:
      typescript: ^5.8.3
  "@module-federation/data-prefetch@0.13.1":
    peerDependenciesMeta:
      react:
        optional: true
      react-dom:
        optional: true
  "@module-federation/data-prefetch@0.9.1":
    peerDependenciesMeta:
      react:
        optional: true
      react-dom:
        optional: true
  "@module-federation/enhanced@0.13.1":
    dependencies:
      "@rspack/core": ^1.2.8
  "@module-federation/enhanced@0.9.1":
    dependencies:
      "@rspack/core": ^1.2.8
  "@module-federation/manifest@0.13.1":
    dependencies:
      typescript: ^5.8.3
  "@module-federation/manifest@0.9.1":
    dependencies:
      typescript: ^5.8.3
  "@module-federation/node@2.7.2":
    dependencies:
      typescript: ^5.8.3
  "@nx/angular@21.0.3":
    dependencies:
      "@module-federation/enhanced": 0.9.1
      "@module-federation/node": ^2.6.26
      "@rspack/core": ^1.2.8
      eslint: ^9.23.0
      nx: 21.0.3
      typescript: ^5.8.3
      webpack: ^5.88.0
  "@nx/eslint@21.0.3":
    dependencies:
      nx: 21.0.3
  "@nx/js@21.0.3":
    dependencies:
      "@types/node": ^22.15.18
      nx: 21.0.3
      typescript: ^5.8.3
  "@nx/module-federation@21.0.3":
    dependencies:
      nx: 21.0.3
      typescript: ^5.8.3
  "@nx/rspack@21.0.3":
    dependencies:
      less: ^4.2.2
      nx: 21.0.3
      react-refresh: ">=0.10.0 <1.0.0"
      typescript: ^5.8.3
  "@nx/web@21.0.3":
    dependencies:
      nx: 21.0.3
  "@nx/webpack@21.0.3":
    dependencies:
      nx: 21.0.3
      typescript: ^5.8.3

yarnPath: .yarn/releases/yarn-4.9.1.cjs
